packets:
  capture_mode: "pcap" # interface or pcap
  source: "/Users/rahul/Desktop/148ms_NAWest_fortnite_5.pcapng"
  direction:
    mode: "ip" # mac or ip
    client_macs:
      - ""
    client_ips:
      - "10.100.113.110/16"

processors:
  header_classifier:
    classes:
      fortnite:
        client_ip: '*'
        server_ip: '13.211.124.142/16'
        client_port: '*'
        server_port: '9000-40000'
        protocol: '17'

sniclassifier:
  classes:
    netflix: '.*\.nflxvideo\.net'